### ISSUE TITLE
員林縣於2015年8月8日改制為縣轄市「員林市」

### ISSUE THREAD

**Issue by TimChen77** [RaymondKYLiu/GoGoVillage#2]
App中的顯示文字為員林縣，應修正為員林市，areaCode不變，經查證依然可以查詢
自動完成街道路名的部分，Api參數帶入員林縣會無法取得路名，可能必須修改為員林市

**Comment by RaymondKYLiu** [comment]
Hi Tim,
Thanks for replying. 👍 
65336cd fixed.

**Comment by TimChen77** [comment]
Sorry, 連issue回報都打錯字, 哈哈哈
應該是彰化縣員林鎮改制為彰化縣員林市
